---
- name: Understanding vars
  hosts: all
  become: yes
  gather_facts: False
  vars: 
    USRNM: playbookuser
    COMM: variable from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout

    - debug:
        var: usrout
