---
- name: Webservers start up
  hosts: webservers
  become: yes
  tasks:
  - name: Install httpd
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Start Service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes 
 
  - name: Copy index file
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html
      backup: yes

        #- name: dbservers start up
        #hosts: dbservers
        #become: yes
        #tasks:
        #- name: Install maria-db server
        #ansible.builtin.yum:
        #name: mariadb-server
        #  state: present

        #  - name: Start mariadb service
        #ansible.builtin.service:
        #name: mariadb
        #state: started
        #enabled: yes 
